dist: bionic
language: go
go:
  - 1.13.x
env:
  - GO111MODULE=off
services:
  - docker
addons:
  apt:
    chrome: stable
before_install:
  - go get -d -t
  - mkdir -p $GOPATH/src/github.com/mailru $GOPATH/src/github.com/goconnectx
  - rm -rf $GOPATH/src/github.com/mailru/easyjson
  - git clone https://github.com/kenshaw/easyjson.git $GOPATH/src/github.com/mailru/easyjson
  - cd $GOPATH/src/github.com/mailru/easyjson
  - go get -d -t
  - git clone https://github.com/goconnectx/cdproto.git $GOPATH/src/github.com/goconnectx/cdproto
  - cd $GOPATH/src/github.com/goconnectx/cdproto
  - go get -d -t
  - go install
  - git clone https://github.com/goconnectx/chromedp.git $GOPATH/src/github.com/goconnectx/chromedp
  - cd $GOPATH/src/github.com/goconnectx/chromedp
  - go get -d -t
  - go install
script:
  - cd $GOPATH/src/github.com/goconnectx/cdproto-gen
  - go build
  - ./cdproto-gen
  - cd $GOPATH/src/github.com/goconnectx/chromedp
  - go test -v
  - go test -c
  - docker run --rm --volume=$PWD:/chromedp --entrypoint=/chromedp/chromedp.test --workdir=/chromedp --env=PATH=/headless-shell chromedp/headless-shell:latest -test.v
